import type { AgentToolDefinition } from "../toolTypes";

export const calendarTools: AgentToolDefinition[] = [
  {
    id: "calendar.list_today",
    name: "List today's events",
    description: "Inspect calendar events scheduled for the current day.",
    domain: "calendar",
    capability: "inspect",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "array",
      description: "Calendar event metadata for today.",
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["workspace", "calendar", "read"],
    examples: [
      {
        title: "Inspect today's schedule",
        input: {},
        expectedOutcome: "Returns today's event metadata.",
      },
    ],
    constraints: ["Read-only contract.", "Does not create or update calendar events."],
  },
  {
    id: "calendar.create_event",
    name: "Create calendar event",
    description: "Create a calendar event after policy evaluation and approval or user pre-authorization.",
    domain: "calendar",
    capability: "schedule",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: true,
    externalEffect: true,
    inputSchema: [
      {
        name: "title",
        type: "string",
        required: true,
        description: "Event title.",
      },
      {
        name: "start",
        type: "date",
        required: true,
        description: "Event start time.",
      },
      {
        name: "end",
        type: "date",
        required: true,
        description: "Event end time.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Created event metadata.",
      fields: [],
    },
    enabled: true,
    version: "1.0.0",
    tags: ["calendar", "write"],
    examples: [
      {
        title: "Schedule focus time",
        input: {
          title: "Focus block",
          start: "2026-07-12T09:00:00Z",
          end: "2026-07-12T10:00:00Z",
        },
        expectedOutcome: "Creates an event only after write policy allows execution or explicit approval.",
      },
    ],
    constraints: ["Requires write policy authorization.", "Auto mode is allowed only while the operation remains undoable."],
  },
  {
    id: "calendar.update_event",
    name: "Update calendar event",
    description: "Update calendar event metadata after policy evaluation and approval or user pre-authorization.",
    domain: "calendar",
    capability: "update",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: true,
    externalEffect: true,
    inputSchema: [
      {
        name: "eventId",
        type: "string",
        required: true,
        description: "Calendar event identifier.",
      },
      {
        name: "fields",
        type: "object",
        required: true,
        description: "Event fields to update.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Updated event metadata.",
      fields: [],
    },
    enabled: true,
    version: "1.0.0",
    tags: ["calendar", "write"],
    examples: [
      {
        title: "Move an event",
        input: { eventId: "event-1", fields: { start: "2026-07-12T11:00:00Z" } },
        expectedOutcome: "Updates an event only after write policy allows execution or explicit approval.",
      },
    ],
    constraints: ["Requires write policy authorization.", "Auto mode is allowed only while the operation remains undoable."],
  },
];
