import type { AgentToolDefinition } from "../toolTypes";

export const githubTools: AgentToolDefinition[] = [
  {
    id: "github.repositories.list",
    name: "List connected GitHub repositories",
    description: "List bounded repository metadata from the user's verified GitHub App installation.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "object",
      description: "At most 20 sanitized repository metadata records.",
      fields: [
        {
          name: "repositories",
          type: "array",
          required: true,
          description: "Sanitized repository identifiers, names, owners, visibility, default branches, and archived flags.",
        },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "repositories", "read", "bounded"],
    examples: [
      {
        title: "Inspect connected repositories",
        input: {},
        expectedOutcome: "Returns up to 20 repositories granted to the verified GitHub App installation.",
      },
    ],
    constraints: [
      "Read-only contract.",
      "Uses authenticated runtime identity only.",
      "Does not accept installation IDs, URLs, paths, tokens, or pagination input.",
      "Does not read source files, commits, branches, issues, pull requests, checks, or actions.",
    ],
  },
  {
    id: "github.issues.list",
    name: "List open GitHub issues",
    description: "List bounded open-issue metadata across the user's verified GitHub App installation.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "object",
      description: "At most 20 sanitized open-issue records across at most 3 scanned repositories.",
      fields: [
        {
          name: "issues",
          type: "array",
          required: true,
          description: "Sanitized repo, issue number, title, state, and last-updated timestamp. No bodies, comments, or user identities.",
        },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "issues", "read", "bounded"],
    examples: [
      {
        title: "Inspect open issues",
        input: {},
        expectedOutcome: "Returns up to 20 open issues across up to 3 repositories granted to the verified GitHub App installation.",
      },
    ],
    constraints: [
      "Read-only contract.",
      "Uses authenticated runtime identity only.",
      "Does not accept installation IDs, URLs, paths, tokens, or pagination input.",
      "Excludes pull requests, issue bodies, comments, labels, assignees, and user identities.",
      "Does not read source files, commits, branches, checks, or actions.",
    ],
  },
  {
    id: "github.epics.list",
    name: "List GitHub epic issues",
    description: "List bounded epic-labeled issue metadata across the user's verified GitHub App installation.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "object",
      description: "At most 20 sanitized epic-issue records across at most 3 scanned repositories.",
      fields: [
        {
          name: "epics",
          type: "array",
          required: true,
          description: "Sanitized repo, issue number, title, epic label, status label, and issue URL. Only issues carrying a label starting with \"epic:\".",
        },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "epics", "roadmap", "read", "bounded"],
    examples: [
      {
        title: "Inspect roadmap epics",
        input: {},
        expectedOutcome: "Returns up to 20 epic-labeled issues across up to 3 repositories granted to the verified GitHub App installation.",
      },
    ],
    constraints: [
      "Read-only contract.",
      "Uses authenticated runtime identity only.",
      "Does not accept installation IDs, URLs, paths, tokens, or pagination input.",
      "Only exposes label values starting with \"epic:\" or \"status:\" — no other labels, assignees, bodies, or comments.",
      "Does not read source files, commits, branches, checks, or actions.",
    ],
  },
  {
    // EPIC-07 (Write Light) -- see docs/adr/ADR-0004-write-boundaries.md.
    id: "github.issues.comment",
    name: "Add a GitHub issue comment",
    description: "Post a comment to an existing issue in a repository the verified GitHub App installation has access to.",
    domain: "github",
    capability: "create",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: false,
    externalEffect: true,
    inputSchema: [
      {
        name: "repo",
        type: "string",
        required: true,
        description: "Repository identifier as owner/name. Must belong to the verified GitHub App installation.",
      },
      {
        name: "issueNumber",
        type: "number",
        required: true,
        description: "Issue number to comment on.",
      },
      {
        name: "body",
        type: "string",
        required: true,
        description: "Comment body, shown to the user as a preview before Run.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "The created comment's id and URL.",
      fields: [
        { name: "commentId", type: "number", required: true, description: "GitHub comment id." },
        { name: "url", type: "string", required: true, description: "URL of the created comment." },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "issues", "write", "epic-07"],
    examples: [
      {
        title: "Comment on an issue",
        input: { repo: "aryan/smartflow", issueNumber: 42, body: "Thanks, looking into this." },
        expectedOutcome: "Posts the exact previewed comment body only after explicit user approval.",
      },
    ],
    constraints: [
      "Requires explicit user approval (\"Run\") after a preview of the exact comment body.",
      "repo must resolve to a repository the verified GitHub App installation has access to.",
      "Rate limited to 5 total GitHub writes per hour per user, shared with github.issues.update.",
      "No bulk writes -- exactly one issue per call.",
      "Every call is logged to agent_write_log before execution.",
    ],
  },
  {
    // EPIC-07 (Write Light) -- see docs/adr/ADR-0004-write-boundaries.md.
    id: "github.issues.update",
    name: "Update a GitHub issue",
    description: "Edit the title, body, and/or labels of an existing issue in a repository the verified GitHub App installation has access to.",
    domain: "github",
    capability: "update",
    mode: "write",
    riskLevel: "medium",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: false,
    externalEffect: true,
    inputSchema: [
      {
        name: "repo",
        type: "string",
        required: true,
        description: "Repository identifier as owner/name. Must belong to the verified GitHub App installation.",
      },
      {
        name: "issueNumber",
        type: "number",
        required: true,
        description: "Issue number to update.",
      },
      {
        name: "title",
        type: "string",
        required: false,
        description: "New issue title. At least one of title/body/labels is required.",
      },
      {
        name: "body",
        type: "string",
        required: false,
        description: "New issue body. At least one of title/body/labels is required.",
      },
      {
        name: "labels",
        type: "array",
        required: false,
        description: "New label set. Every label must already exist on the repository -- unrecognized labels reject the whole update.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "The updated issue's number and URL.",
      fields: [
        { name: "issueNumber", type: "number", required: true, description: "Updated issue number." },
        { name: "url", type: "string", required: true, description: "URL of the updated issue." },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "issues", "write", "epic-07"],
    examples: [
      {
        title: "Relabel an issue",
        input: { repo: "aryan/smartflow", issueNumber: 42, labels: ["bug", "priority:high"] },
        expectedOutcome: "Applies the exact previewed title/body/label change only after explicit user approval.",
      },
    ],
    constraints: [
      "Requires explicit user approval (\"Run\") after a preview of the exact title/body/label change.",
      "repo must resolve to a repository the verified GitHub App installation has access to.",
      "labels must be a subset of the repository's actual label set -- validated live per request, not cached.",
      "Rate limited to 5 total GitHub writes per hour per user, shared with github.issues.comment.",
      "No bulk writes -- exactly one issue per call.",
      "Does not create issues, comments, pull requests, or touch files/code.",
      "Every call is logged to agent_write_log before execution.",
    ],
  },
  {
    // EPIC-08 Slice 1 -- see docs/roadmap/epic-08-write-code-design-v1.md.
    id: "github.files.read",
    name: "Read a GitHub file",
    description: "Read one existing UTF-8 text file's content, blob SHA, and current branch commit SHA from a repository the verified GitHub App installation has access to.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [
      {
        name: "repo",
        type: "string",
        required: true,
        description: "Repository identifier as owner/name. Must belong to the verified GitHub App installation.",
      },
      {
        name: "path",
        type: "string",
        required: true,
        description: "Repository-relative POSIX path to an existing text file. Protected paths (secrets, keys, .git/**, .github/workflows/**) are denied.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "The file's content and the identifiers needed to build a code-change proposal.",
      fields: [
        { name: "repo", type: "string", required: true, description: "Repository identifier as owner/name." },
        { name: "path", type: "string", required: true, description: "The requested repository-relative path." },
        { name: "branch", type: "string", required: true, description: "The repository's default branch, read from." },
        { name: "blobSha", type: "string", required: true, description: "GitHub's blob SHA for the exact file content returned." },
        { name: "commitSha", type: "string", required: true, description: "The branch's current head commit SHA at read time." },
        { name: "content", type: "string", required: true, description: "The file's UTF-8 text content." },
        { name: "size", type: "number", required: true, description: "Content size in bytes." },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "files", "read", "epic-08", "slice-1"],
    examples: [
      {
        title: "Read an existing file before proposing a change",
        input: { repo: "aryan/smartflow", path: "README.md" },
        expectedOutcome: "Returns the file's current content, blob SHA, and branch commit SHA for a proposal.",
      },
    ],
    constraints: [
      "Read-only contract -- no branch, commit, or mutation of any kind.",
      "Always reads from the repository's default branch; does not accept a caller-selected ref.",
      "Rejects binary content, non-UTF-8 content, and files larger than 128 KiB.",
      "Rejects protected paths by default: secrets, credentials, private keys, certificates, .git/**, and .github/workflows/**.",
      "repo must resolve to a repository the verified GitHub App installation has access to.",
      "Exactly one file per call -- no directory listing, no multi-file reads.",
    ],
  },
  {
    // EPIC-08 Slice 3 -- see docs/adr/ADR-0005-code-write-mutation-boundary.md.
    id: "github.files.update",
    name: "Update a GitHub file",
    description: "Commit an approved content change to one existing text file, on one newly created non-default branch, as one commit, using the GitHub Contents API.",
    domain: "github",
    capability: "update",
    mode: "write",
    riskLevel: "high",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: false,
    externalEffect: true,
    inputSchema: [
      {
        name: "proposalId",
        type: "string",
        required: true,
        description: "The content-addressed identifier of the approved proposal this mutation corresponds to.",
      },
      {
        name: "repo",
        type: "string",
        required: true,
        description: "Repository identifier as owner/name. Must belong to the verified GitHub App installation.",
      },
      {
        name: "path",
        type: "string",
        required: true,
        description: "Repository-relative POSIX path to the existing text file being updated.",
      },
      {
        name: "proposedContent",
        type: "string",
        required: true,
        description: "The exact new file content. Must match the digest recorded when the proposal was approved.",
      },
      {
        name: "commitMessage",
        type: "string",
        required: false,
        description: "Optional bounded commit message.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Identity of the created branch and commit once the mutation succeeds.",
      fields: [
        { name: "repo", type: "string", required: true, description: "Repository identifier as owner/name." },
        { name: "path", type: "string", required: true, description: "The updated repository-relative path." },
        { name: "branch", type: "string", required: true, description: "The newly created non-default branch." },
        { name: "commitSha", type: "string", required: true, description: "The new commit SHA." },
        { name: "blobSha", type: "string", required: true, description: "The new file blob SHA." },
        { name: "commitUrl", type: "string", required: true, description: "The GitHub URL for the new commit." },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "files", "write", "epic-08", "slice-3"],
    examples: [
      {
        title: "Commit an approved README change",
        input: { proposalId: "code-proposal:...", repo: "aryan/smartflow", path: "README.md", proposedContent: "..." },
        expectedOutcome: "Creates a new non-default branch and one commit containing the approved change.",
      },
    ],
    constraints: [
      "Exactly one existing file, one newly created non-default branch, one commit -- never the default branch.",
      "Requires a server-verifiable approval record (agent_code_proposal_approvals); baseBlobSha, baseCommitSha, proposedContentDigest, riskLevel, and expiresAt are never accepted as trusted request fields.",
      "The Worker independently re-derives every stored approval fact and revalidates the current branch/file state immediately before mutation; a stale, expired, mismatched, or already-consumed approval fails closed.",
      "No pull request, merge, automatic retry, or rollback -- one approval authorizes exactly one attempt.",
      "Rejects protected paths, binary content, non-UTF-8 content, and files larger than 128 KiB, using the same rules as github.files.read.",
      "If branch creation succeeds but the commit fails, the branch is left in place for inspection and is never automatically deleted or retried.",
    ],
  },
  {
    // ENG-04 -- see docs/architecture/notes/eng-04-companion-chat-approval-wiring-v1.md.
    // riskLevel "high": this authorizes an unattended, real-repo, real-cost
    // Claude Code run with no mid-execution pause, matching github.files.update's
    // own risk classification for real repository mutation -- the fact that
    // THIS call only submits the task (the actual mutation happens later,
    // out of band, once the companion runs it) does not lower the risk of
    // what approving it sets in motion.
    id: "engineering.task.propose",
    name: "Submit an engineering task",
    description: "Submits an approved, unattended engineering task to the SmartFlow coding companion. The companion runs Claude Code end to end (edit, commit, push to a fresh branch) with no mid-execution pause, then reports back a verified result. Never merges to the default branch.",
    domain: "github",
    capability: "create",
    mode: "write",
    riskLevel: "high",
    requiresApproval: true,
    approvalScope: "single_step",
    reversible: false,
    externalEffect: true,
    inputSchema: [
      {
        name: "repo",
        type: "string",
        required: true,
        description: "Repository identifier as owner/name. Must belong to the verified GitHub App installation AND the companion's own local allowlist.",
      },
      {
        name: "instruction",
        type: "string",
        required: true,
        description: "The engineering task instruction Claude Code will receive verbatim.",
      },
      {
        name: "taskClass",
        type: "string",
        required: true,
        description: "A caller-supplied label for the kind of change (e.g. docs_fix, test_fix). Logged only in this slice -- not yet used for any auto/ask/off policy.",
      },
    ],
    outputSchema: {
      type: "object",
      description: "Confirmation that the task was queued -- not the task's result. The actual outcome arrives later as a separate chat message once the companion reports back.",
      fields: [
        { name: "id", type: "string", required: true, description: "The created engineering_tasks row id." },
        { name: "status", type: "string", required: true, description: "Always 'pending' at submission time." },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "engineering-task", "write", "eng-04"],
    examples: [
      {
        title: "Submit a documentation fix task",
        input: { repo: "aryan/smartflow", instruction: "Fix the typo in README.md's install section.", taskClass: "docs_fix" },
        expectedOutcome: "Creates a pending engineering_tasks row; the companion picks it up on its next poll.",
      },
    ],
    constraints: [
      "Runs entirely unattended once approved -- no mid-execution pause. Approval here is the only gate; there is no second approval before the companion acts.",
      "The companion always creates its own uniquely-named branch and never touches, checks out, commits to, or merges into the default branch or any other existing branch, under any circumstance.",
      "Merging the resulting branch is out of scope -- it always remains a manual PR.",
      "The companion independently re-checks its own repository allowlist before running anything; a repo accepted here is not automatically trusted there.",
      "No auto/ask/off standing authorization in this slice -- every task requires this same explicit approval, regardless of taskClass.",
    ],
  },
  {
    id: "github.pulls.list",
    name: "List open GitHub pull requests",
    description: "List bounded open-pull-request metadata across the user's verified GitHub App installation.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "object",
      description: "At most 20 sanitized open-pull-request records across at most 3 scanned repositories.",
      fields: [
        {
          name: "pullRequests",
          type: "array",
          required: true,
          description: "Sanitized repo, PR number, title, state, draft flag, and last-updated timestamp. No diffs, reviews, or comments.",
        },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "pulls", "read", "bounded"],
    examples: [
      {
        title: "Inspect open pull requests",
        input: {},
        expectedOutcome: "Returns up to 20 open pull requests across up to 3 repositories granted to the verified GitHub App installation.",
      },
    ],
    constraints: [
      "Read-only contract.",
      "Uses authenticated runtime identity only.",
      "Does not accept installation IDs, URLs, paths, tokens, or pagination input.",
      "Excludes issues, diffs, reviews, comments, labels, assignees, and user identities.",
      "Does not read source files, commits, branches, checks, or actions.",
    ],
  },
  {
    id: "github.workflow_runs.list",
    name: "List recent GitHub Actions workflow runs",
    description: "List bounded recent workflow-run status across the user's verified GitHub App installation.",
    domain: "github",
    capability: "read",
    mode: "read",
    riskLevel: "none",
    requiresApproval: false,
    approvalScope: "view_only",
    reversible: true,
    externalEffect: false,
    inputSchema: [],
    outputSchema: {
      type: "object",
      description: "At most 10 sanitized recent workflow-run records across at most 3 scanned repositories, ordered by recency.",
      fields: [
        {
          name: "workflowRuns",
          type: "array",
          required: true,
          description: "Sanitized repo, workflow name, status, conclusion, and last-updated timestamp. No logs, artifacts, or job details.",
        },
      ],
      containsSensitiveData: false,
    },
    enabled: true,
    version: "1.0.0",
    tags: ["github", "actions", "workflow_runs", "read", "bounded"],
    examples: [
      {
        title: "Inspect recent workflow runs",
        input: {},
        expectedOutcome: "Returns up to 10 of the most recent workflow runs across up to 3 repositories granted to the verified GitHub App installation.",
      },
    ],
    constraints: [
      "Read-only contract.",
      "Uses authenticated runtime identity only.",
      "Does not accept installation IDs, URLs, paths, tokens, or pagination input.",
      "Excludes run logs, artifacts, job details, and user identities.",
      "Does not read source files, commits, branches, issues, or pull requests.",
    ],
  },
];
